//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Independiente.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Independiente.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carátula de estado de cuenta.
        /// </summary>
        public static string AccountStatementCoverPageLabelGlobal {
            get {
                return ResourceManager.GetString("AccountStatementCoverPageLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string AddButtonGlobal {
            get {
                return ResourceManager.GetString("AddButtonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string AddressLabelGlobal {
            get {
                return ResourceManager.GetString("AddressLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono alternativo.
        /// </summary>
        public static string AlternativePhoneNumberLabelGlobal {
            get {
                return ResourceManager.GetString("AlternativePhoneNumberLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta bancaria de cobros.
        /// </summary>
        public static string BankChargeAccountLabelGlobal {
            get {
                return ResourceManager.GetString("BankChargeAccountLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta bancaria de depósitos.
        /// </summary>
        public static string BankDepositAccountLabelGlobal {
            get {
                return ResourceManager.GetString("BankDepositAccountLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string BankLabelGlobal {
            get {
                return ResourceManager.GetString("BankLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string BankPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("BankPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string BirthDayLabelGlobal {
            get {
                return ResourceManager.GetString("BirthDayLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string CancelButtonGlobal {
            get {
                return ResourceManager.GetString("CancelButtonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudad.
        /// </summary>
        public static string CityLabelGlobal {
            get {
                return ResourceManager.GetString("CityLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xalapa.
        /// </summary>
        public static string CityPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("CityPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clients.
        /// </summary>
        public static string ClientsLabelGlobal {
            get {
                return ResourceManager.GetString("ClientsLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de contacto.
        /// </summary>
        public static string ContactDataLabelGlobal {
            get {
                return ResourceManager.GetString("ContactDataLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de crédito.
        /// </summary>
        public static string CreditApplicationLabelGlobal {
            get {
                return ResourceManager.GetString("CreditApplicationLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de crédito.
        /// </summary>
        public static string CreditDetailsLabelGlobal {
            get {
                return ResourceManager.GetString("CreditDetailsLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURP.
        /// </summary>
        public static string CURPLabelGlobal {
            get {
                return ResourceManager.GetString("CURPLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AAAA111111HHZZXXZ0.
        /// </summary>
        public static string CURPPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("CURPPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 01/01/2000.
        /// </summary>
        public static string DatePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("DatePlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentación.
        /// </summary>
        public static string DocumentationLabelGlobal {
            get {
                return ResourceManager.GetString("DocumentationLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string EditButtonGlobal {
            get {
                return ResourceManager.GetString("EditButtonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string EmailAddressLabelGlobal {
            get {
                return ResourceManager.GetString("EmailAddressLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ejemplo@gmail.com.
        /// </summary>
        public static string EmailAddressPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("EmailAddressPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financiera Independiente.
        /// </summary>
        public static string FinancialNameLabelGlobal {
            get {
                return ResourceManager.GetString("FinancialNameLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string FullLastNameLabelGlobal {
            get {
                return ResourceManager.GetString("FullLastNameLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hernández Valdés.
        /// </summary>
        public static string FullLastNamePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("FullLastNamePlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar solicitud.
        /// </summary>
        public static string GenerateApplicationButtonLocal {
            get {
                return ResourceManager.GetString("GenerateApplicationButtonLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de contratación.
        /// </summary>
        public static string HiringDateLabelGlobal {
            get {
                return ResourceManager.GetString("HiringDateLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INE.
        /// </summary>
        public static string INELabelGlobal {
            get {
                return ResourceManager.GetString("INELabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLABE interbancaria.
        /// </summary>
        public static string InterBankCLABELabelGlobal {
            get {
                return ResourceManager.GetString("InterBankCLABELabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XXXX-XXXX-XXXX-XXXX.
        /// </summary>
        public static string InterBankCLABEPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("InterBankCLABEPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa de interés (%).
        /// </summary>
        public static string InteresRateLabelGlobal {
            get {
                return ResourceManager.GetString("InteresRateLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 00.00.
        /// </summary>
        public static string InteresRatePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("InteresRatePlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto solicitado.
        /// </summary>
        public static string LoanAmountLabelGlobal {
            get {
                return ResourceManager.GetString("LoanAmountLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazo.
        /// </summary>
        public static string LoanTermLabelGlobal {
            get {
                return ResourceManager.GetString("LoanTermLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 00.
        /// </summary>
        public static string LoanTermPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("LoanTermPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string LogOutButtonLocal {
            get {
                return ResourceManager.GetString("LogOutButtonLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string MaternalSurnameLabelGlobal {
            get {
                return ResourceManager.GetString("MaternalSurnameLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valdés.
        /// </summary>
        public static string MaternalSurnamePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("MaternalSurnamePlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a $1000.00.
        /// </summary>
        public static string MoneyPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("MoneyPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos mensuales.
        /// </summary>
        public static string MontlyIncomeLabelGlobal {
            get {
                return ResourceManager.GetString("MontlyIncomeLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string NameLabelGlobal {
            get {
                return ResourceManager.GetString("NameLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juan.
        /// </summary>
        public static string NamePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("NamePlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia.
        /// </summary>
        public static string NeighborhoodLabelGlobal {
            get {
                return ResourceManager.GetString("NeighborhoodLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colonia centro.
        /// </summary>
        public static string NeighborhoodPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("NeighborhoodPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string NextButtonGlobal {
            get {
                return ResourceManager.GetString("NextButtonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordLabelGlobal {
            get {
                return ResourceManager.GetString("PasswordLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la contraseña.
        /// </summary>
        public static string PasswordPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("PasswordPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string PaternalSurnameLabelGlobal {
            get {
                return ResourceManager.GetString("PaternalSurnameLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hernández.
        /// </summary>
        public static string PaternalSurnamePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("PaternalSurnamePlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia de pago.
        /// </summary>
        public static string PaymentFrecuencyLabelGlobal {
            get {
                return ResourceManager.GetString("PaymentFrecuencyLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia de pago.
        /// </summary>
        public static string PaymentFrecuencyPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("PaymentFrecuencyPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información personal.
        /// </summary>
        public static string PersonalDataLabelGlobal {
            get {
                return ResourceManager.GetString("PersonalDataLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de teléfono.
        /// </summary>
        public static string PhoneNumberLabelGlobal {
            get {
                return ResourceManager.GetString("PhoneNumberLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1234567890.
        /// </summary>
        public static string PhoneNumberPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promoción.
        /// </summary>
        public static string PromotionLabelGlobal {
            get {
                return ResourceManager.GetString("PromotionLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promoción.
        /// </summary>
        public static string PromotionPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("PromotionPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobante de domicilio.
        /// </summary>
        public static string ProofOfAddressLabelGlobal {
            get {
                return ResourceManager.GetString("ProofOfAddressLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto de referencia.
        /// </summary>
        public static string ReferenceContactLabelGlobal {
            get {
                return ResourceManager.GetString("ReferenceContactLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parentesco.
        /// </summary>
        public static string RelationshipLabelGlobal {
            get {
                return ResourceManager.GetString("RelationshipLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parentesco.
        /// </summary>
        public static string RelationshipPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("RelationshipPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC.
        /// </summary>
        public static string RFCLabelGlobal {
            get {
                return ResourceManager.GetString("RFCLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XAXX010101000.
        /// </summary>
        public static string RFCPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("RFCPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string SaveButtonGlobal {
            get {
                return ResourceManager.GetString("SaveButtonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar cliente por RFC .
        /// </summary>
        public static string SearchClientByRFCPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("SearchClientByRFCPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string SignUpButtonLocal {
            get {
                return ResourceManager.GetString("SignUpButtonLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string StateLabelGlobal {
            get {
                return ResourceManager.GetString("StateLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veracruz.
        /// </summary>
        public static string StatePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("StatePlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        public static string StreetLabelGlobal {
            get {
                return ResourceManager.GetString("StreetLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle 123.
        /// </summary>
        public static string StreetPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("StreetPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string WelcomeGreetingLabelLocal {
            get {
                return ResourceManager.GetString("WelcomeGreetingLabelLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de trabajo.
        /// </summary>
        public static string WorkCenterLabelGlobal {
            get {
                return ResourceManager.GetString("WorkCenterLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Independiente.
        /// </summary>
        public static string WorkCenterPlaceHolderGlobal {
            get {
                return ResourceManager.GetString("WorkCenterPlaceHolderGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puesto.
        /// </summary>
        public static string WorkCenterRoleLabelGlobal {
            get {
                return ResourceManager.GetString("WorkCenterRoleLabelGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asesor.
        /// </summary>
        public static string WorkCenterRolePlaceHolderGlobal {
            get {
                return ResourceManager.GetString("WorkCenterRolePlaceHolderGlobal", resourceCulture);
            }
        }
    }
}
